### ISSUE TITLE
BlockState Filters

### ISSUE THREAD

**Issue by SoniEx2** [eNByeX/NoteBetter#3]
Currently the instrument configuration for blocks can only filter block names. A way to filter based on BlockState (essentially the 1.8 version of the 0-15 block metadata) is needed.

There are 2 formats I can use. Which one should I go with?

Format 1: (This is probably closer to the way Mojang would do it.)

``` json
{
    "block": {
        "name": "minecraft:stone",
        "state": {
            "variant": "something"
        }
    },
    "sound": "minecraft:note.pling"
}
```

Format 2: (This is closer to the way I'm currently doing it. Slightly "flatter" when compared to the above.)

``` json
{
    "block": "minecraft:stone",
    "sound": "minecraft:note.pling",
    "state": {
        "variant": "something"
    }
}
```

Obviously, this is irrelevant when it comes to materials, as, last I checked, different states of the same block can't have different materials.

**Comment by skyem123** [comment]
Well, I like Format 2 more.

**Comment by SoniEx2** [comment]
``` json
{
  "block": "minecraft:stone",
  "states": [
    {"variant": {"something": "something"}, "sound": {...}},
    {"variant": {}, "sound": {...}}
  ],
  "sound": {...}
}
```

Without any difference between an empty variant and `"sound"` outside `states` list.
